require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

project '1000jours', {
  'DebugDev' => :debug,
  'DebugRec' => :debug,
  'DebugProd' => :debug,
  'ReleaseDev' => :release,
  'ReleaseRec' => :release,
  'ReleaseProd' => :release
}

target '1000jours' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Uncomment to opt-in to using Flipper
  #
  # if !ENV['CI']
    # use_flipper!({'Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1'}, configurations: ['DebugDev', 'DebugRec', 'DebugProd', 'ReleaseDev', 'ReleaseRec', 'ReleaseProd'])
    # post_install do |installer|
    #   flipper_post_install(installer)
    # end
  # end
end
