app-strapi:
  ~needs: [restore]
  ~preDeploy.cleaner:
    match:
      kind: Deployment  
    value: true
  volumes:
    - name: uploads
      emptyDir: {}
  volumeMounts:
    - mountPath: /app/public/uploads
      name: uploads

jobs:
  runs:
    create-db:
      use: create-db
    restore:
      ~needs: [create-db]
      use: pg-restore
      checkout: false
      with:
        mountPath: /mnt/restore
        restorePath: "${LATEST}/prod_db.psql.gz"
      volumeMounts:
        - name: restore
          mountPath: /mnt/restore
          readOnly: true
      volumes:
        - name: restore
          csi:
            driver: file.csi.azure.com
            readOnly: true
            volumeAttributes:
              secretName: les1000joursprodserver-backup-credentials
              shareName: les1000jprodsrv2-backup-restore