app-strapi:
  ~needs: [pg, build-strapi, restore]
  ~preDeploy.cleaner:
    match:
      kind: Deployment
    value: true
  volumes:
    - name: uploads
      emptyDir: {}
  volumeMounts:
    - mountPath: /app/public/uploads
      name: uploads
  envFrom:
    - secretRef:
        name: strapi
    - configMapRef:
        name: strapi-configmap
    - secretRef:
        name: azure-les1000jours-volume
    - secretRef:
        name: "pg-app"

jobs:
  runs:
    restore:
      ~needs: [pg]
      use: pg-restore
      checkout: false
      with:
        mountPath: /mnt/restore
        restorePath: "${LATEST}/prod_db.psql.gz"
        pgAdminUserSecretRefName: pg-superuser
      volumeMounts:
        - name: restore
          mountPath: /mnt/restore
          readOnly: true
      volumes:
        - name: restore
          csi:
            driver: file.csi.azure.com
            readOnly: true
            volumeAttributes:
              secretName: les1000joursprodserver-backup-credentials
              shareName: les1000jprodsrv2-backup-restore
