app-strapi:
  needs: [restore]
  volumes:
    - name: uploads
      emptyDir: {}
  volumeMounts:
    - mountPath: /app/public/uploads
      name: uploads

jobs:
  runs:
    # create-db:
    #   use: SocialGouv/kube-workflow/jobs/create-db@v1
    #   with:
    #     pgAdminSecretRefName: azure-pg-admin-user
    restore:
      # needs: [create-db]
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/pg-restore
      run: |
        sleep 240
      checkout: false
      with:
        mountPath: /mnt/restore
        restorePath: "${LATEST}/prod_db.psql.gz"
        pgAdminSecretRefName: azure-pg-admin-user
      volumeMounts:
        - name: restore
          mountPath: /mnt/restore
          readOnly: true
      volumes:
        - name: restore
          persistentVolumeClaim:
            claimName: les1000jours-backup-restore
