global:
  namespace: les1000jours
  host: "les1000jours.fabrique.social.gouv.fr"

app-strapi:
  certSecretName: strapi-cache-crt
  host: "backoffice-les1000jours.fabrique.social.gouv.fr"
  addVolumes:
    - uploads
  volumeMounts:
    - name: uploads
      mountPath: /app/public/uploads
  autoscale:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
