global:
  namespace: les1000jours
  host: "les1000jours.fabrique.social.gouv.fr"

app-strapi:
  replicas: 1 # mandatory because volume is RWO
  strategyType: Recreate # idem
  addVolumes:
    - uploads
  volumeMounts:
    - name: uploads
      mountPath: /app/public/uploads
  securityContext:
    fsGroup: 1001

pg:
  cnpg-cluster:
    recovery:
      enabled: true
      ~tpl~database: "{{ .Values.global.pgDatabase }}"
      ~tpl~owner: "{{ .Values.global.pgUser }}"
      secretName: "pg-db"
      barmanObjectStore:
        ~tpl~destinationPath: "s3://les1000jours-prod-backups/les1000jours"
        s3Credentials:
          accessKeyId:
            ~tpl~name: "les1000jours-prod-backups-access-key"
            key: bucket_access_key
          secretAccessKey:
            ~tpl~name: "les1000jours-prod-backups-access-key"
            key: bucket_secret_key
          region:
            ~tpl~name: "les1000jours-prod-backups-access-key"
            key: bucket_region
