global:
  namespace: les1000jours
  host: "les1000jours.fabrique.social.gouv.fr"

app-strapi:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  replicas: 1 # mandatory because volume is RWO
  strategyType: Recreate # idem
  addVolumes:
    - uploads
  volumeMounts:
    - name: uploads
      mountPath: /app/public/uploads
  securityContext:
    fsGroup: 1001

pg:
  cnpg-cluster:
    resources:
      requests:
        cpu: 100mi
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 1Gi
