apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hasura-sealed-secret
spec:
  encryptedData:
    HASURA_GRAPHQL_ADMIN_SECRET: AgAsYUsZEOgJS8h6jCJ2eTR4aVPecojja9aoGnBquYTbbBhooS6ztD/NS2MzBScD8i7xVMZt9ZjUGdtx/pEUKSj3ewnVDxbV9phsQjCvHND53/SIe8HXaxlGR7z+sbwUsVVwaJjQ59WnX3/aL5mB0+Je+6I921ahZ2KoOpcZ8hSq2ulfmoMdZ9zc98AjQmWbwv6VnWRxp8vs5FIdlkN1x0uPKvYAkQeGTxvLtz+WnfAdTZYFibl3jMKKj27PN1G2lHJql5llqLw67oRrosrLAzKLuuOmFdaKDi5iJhZbqZ5GqWwDw4yfQA5lytXML6eV0ekHJA4HruwcnVZlGBjsK39WuNzI8rLFfaYvvRUTUXjOMsGgMwO0DD5cHVrOYO38uyQ9Vnq7ZgU6X3fTIOLwnb+FIn0xEtFfY165S2hjNrCU5td0gUE+mgtpSPS7Et3QzEi1rJDx7x+mslzldTJsCwWS9eji3TV/EAJT8Tsxn/SX5AyCnamMPcsclBlI7UmkMXszaJ1U9jux/Oa/pfVrA+CYWzu3TjVwS8vRcv9eInT0y2HH15/asRMmJbJN03Qj0z3uTFusPgXvlBidStRA/L+O1qZfQtWh8TD+58DTssg/AI+C8tXIyYYmCbTpTqAVQdpbRjwcgQbzqFWOG7NWT4fJwceooNrVC3zxhKQtD16kntDYWLK8jel+g4bWaSgxbLdNnLoYAn4/jNrl1lBwqQr2jpl50jlvXhMLmIEG9+K1OJfmPwjudjOH
  template:
    metadata:
      creationTimestamp: null
      name: hasura-sealed-secret
    type: Opaque