kind: ConfigMap
apiVersion: v1
metadata:
  name: strapi-configmap
data:
  STRAPI_LOG_LEVEL: "info"
  NODE_ENV: "production"
  SENTRY_DSN: "https://5dbac413000f4a43a073841acebc82f5@sentry.fabrique.social.gouv.fr/55"
