apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: strapi-sealed-secret
spec:
  encryptedData:
    hello: AgABuHuoDnoQInNf6zzqknt1PSKqcPycEClW4KFs9RXVW12q1p52o0Gm9sJyKzQX0aYqPVNzJP8h6GyY01W7p7OtKL5VLaLpVvQm1Dxai8yz+5WHrZ8z0/dOtmuM9hnBAH7VoLj363A06/gu5B4Ps+ESk+rX3jibixhAfuOpe3cylr1a5k6bY1hK1MoniYDjPyG0z6tTQWD6JlB2xFvAABuMiSyASr/ffH6xoyz9+KWYd1blADkkJmSnyoVGcUvL9ihzgDryQq7/Ukqwqb9Hcc79zfwh2a2NAyy0juvjTF/JjNYHiC1JSdUQsuLKCc3WWRiH5jjN+JIfqjMaZwKlXaLeXPcXxEp0799F4w/24AnBBVNnowYZv4vxqUNdygwEaPEp07VYKAdWAOhwwv8VIURcteGPohFvNASf46a+r2dvrzynQmx6N57aPJr9eC3VC2B1G6kshG18s4TKeJPJsiQiHXAdVwpjhdk/nsW3hkzv4g8+TsIH/cO4cdoFsSZf2FAaHXgB2/SxOY9r3eGjaKASVBKXD/Hd55ceK+K5gHdg+M60JngYaH/6E2VujzAuO6EkzlU0LNOeOxfWy0hBhjK0CKg4T7dikCJ6d6Aox+0K7MgJgPWEJyiXJNL/wYORmSkql87lDMx2BZLQyiBxaokJumk3KY8TXxhy13t0A8yYr9QKAIH75GCN9Jn7noZYdTJC/+hQQA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: strapi-sealed-secret
