# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

submit_for_review true
app_identifier "com.fabrique.millejours"
force true
automatic_release true
