app-strapi:
  host: "backoffice-1000jours-preprod.dev.fabrique.social.gouv.fr"
  addVolumes:
    - uploads
  volumeMounts:
    - mountPath: /app/public/uploads
      name: uploads
  envFrom:
    - secretRef:
        name: strapi
    - configMapRef:
        name: strapi-configmap
    - secretRef:
        name: azure-les1000jours-volume
    - secretRef:
        name: "pg-app"
