app-strapi:
  host: "backoffice-1000jours-preprod.dev.fabrique.social.gouv.fr"
  ~needs: [pg, build-strapi]
  addVolumes:
    - uploads
  volumeMounts:
    - mountPath: /app/public/uploads
      name: uploads

pg:
  ~chart: pg
  cnpg-cluster:
    recovery:
      enabled: true
      barmanObjectStore:
        ~tpl~destinationPath: "s3://les1000jours-prod-backups/les1000jours"
        s3Credentials:
          accessKeyId:
            ~tpl~name: "les1000jours-prod-backups-access-key"
            key: bucket_access_key
          secretAccessKey:
            ~tpl~name: "les1000jours-prod-backups-access-key"
            key: bucket_secret_key
          region:
            ~tpl~name: "les1000jours-prod-backups-access-key"
            key: bucket_region
 
