projectName: les1000jours

dependencies:
  fabrique:
    import: SocialGouv/kontinuous/plugins/fabrique
    dependencies:
      contrib:
        patches:
          reloader:
            enabled: false