projectName: les1000jours
ciNamespace: ci-les1000jours

dependencies:
  fabrique:
    extends:
      - name: buildkit-service
    dependencies:
      contrib:
        preDeploy:
          importSecrets:
            options:
              secrets:
                les1000joursprodserver-backup-credentials:
                  env: dev
                  required: true
