projectName: les1000jours
ciNamespace: ci-les1000jours

dependencies:
  fabrique:
    extends:
    - name: ovh
      ifEnv: [dev,preprod]
    - name: buildkit-service
      ifEnv: [dev,preprod]
    dependencies: # todo: remove
      contrib:
        preDeploy:
          importSecrets:
            options:
              secrets:
                les1000joursprodserver-backup-credentials:
                  env: dev
