global:
  registry: ghcr.io
  imageProject: socialgouv

pg:
  ~chart: pg

app-strapi:
  ~chart: app
  host: "backoffice-{{ .Values.global.host }}"
  imagePackage: strapi
  containerPort: 1337
  probesPath: /_health
  resources:
    requests:
      cpu: 0.5
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  # startupProbe:
  #   initialDelaySeconds: 30
  envFrom:
    - secretRef:
        name: strapi
    - configMapRef:
        name: strapi-configmap
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
  env:
    - name: BACKOFFICE_URL
      value: "https://backoffice-{{ .Values.global.host }}"
    - name: DATABASE_CLIENT
      value: "postgres"
    - name: DATABASE_NAME
      value: "$(PGDATABASE)"
    - name: DATABASE_HOST
      value: "$(PGHOST)"
    - name: DATABASE_PORT
      value: "$(PGPORT)"
    - name: DATABASE_USERNAME
      value: "$(PGUSER)"
    - name: DATABASE_PASSWORD
      value: "$(PGPASSWORD)"
    - name: DATABASE_SSL
      value: "true"
    - name: TZ
      value: "Europe/Paris"

deactivate:
  jobs-deactivate:
    runs:
      deactivate:
        with:
          db: true
