global:
  imageProject: 1000jours
  pgUser: 1000jours
  pgDatabase: 1000jours

pg:
  ~chart: pg

app-strapi:
  ~chart: app
  host: "backoffice-{{ .Values.global.host }}"
  ~needs: [pg, build-strapi]
  imagePackage: strapi
  containerPort: 1337
  probesPath: /_health
  resources:
    requests:
      cpu: 0.5
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  # startupProbe:
  #   initialDelaySeconds: 30
  envFrom:
    - secretRef:
        name: strapi
    - configMapRef:
        name: strapi-configmap
    - secretRef:
        name: "pg-app"
    - secretRef:
        name: azure-les1000jours-volume
  env:
    - name: BACKOFFICE_URL
      value: "https://backoffice-{{ .Values.global.host }}"
    - name: DATABASE_CLIENT
      value: "postgres"
    - name: DATABASE_NAME
      value: "{{ .Values.global.pgDatabase }}"
    - name: DATABASE_HOST
      value: "$(PGHOST)"
    - name: DATABASE_PORT
      value: "$(PGPORT)"
    - name: DATABASE_USERNAME
      value: "{{ .Values.global.pgUser }}"
    - name: DATABASE_PASSWORD
      value: "$(PGPASSWORD)"
    - name: DATABASE_SSL
      value: "true"
    - name: TZ
      value: "Europe/Paris"

jobs:
  runs:
    build-strapi:
      use: build
      with:
        context: ./back/strapi
        imagePackage: strapi
