name: Publish on ExpoGo (PreProd)
# on:
#   push:
#     branches:
#       - 'master'
#     paths:
#       - 'front/**'
#       - '.github/workflows/expo-publish-preprod.yml'
on:
  push:
    tags:
      - v*
  workflow_dispatch:
    name:
      description: 'Manual workflow'

concurrency:
  group: expo-preproduction
  cancel-in-progress: true

jobs:
  Publish:
    name: Publish PreProd
    runs-on: ubuntu-latest
    env:
      API_URL: https://backoffice-1000jours-preprod.dev.fabrique.social.gouv.fr
      CLEAR_STORAGE: false
      MATOMO_APPLICATION_ID: 46
      MATOMO_ENABLED: true
      MATOMO_URL: https://matomo.fabrique.social.gouv.fr/
      SENTRY_DSN: https://d622675092bb449481c8016cab8ffd08@sentry.fabrique.social.gouv.fr/62
      SENTRY_ENABLED: true
      SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      DEEPLINK_DOMAIN: 1000jours.fabrique.social.gouv.fr
      DEEPLINK_PATH: app-millejours
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - name: Yarn
        run: |
          cd front
          yarn install
          yarn publish-preprod
          
