name: Expo Build Dev
on:
  workflow_dispatch:
    name:
      description: 'Manual workflow'

jobs:
  Build-android:
    name: Build and publish Android for staging
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.API_URL }}
      CLEAR_STORAGE: ${{ secrets.CLEAR_STORAGE }}
      MATOMO_APPLICATION_ID: ${{ secrets.MATOMO_APPLICATION_ID }}
      MATOMO_URL: ${{ secrets.MATOMO_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - name: Yarn
        run: |
          cd front
          yarn install
          yarn build-staging:android

  Build-ios:
    name: Build and publish iOS for staging
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.API_URL }}
      CLEAR_STORAGE: ${{ secrets.CLEAR_STORAGE }}
      MATOMO_APPLICATION_ID: ${{ secrets.MATOMO_APPLICATION_ID }}
      MATOMO_URL: ${{ secrets.MATOMO_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - name: Yarn
        run: |
          cd front
          yarn install
          yarn build-staging:ios
