name: Mobile Tests

on:
  pull_request:

jobs:
  mobile-tests:
    name: Mobile Tests
    runs-on: ubuntu-latest
    env:
      MATOMO_APPLICATION_ID: 46
      MATOMO_ENABLED: false
      MATOMO_URL: https://matomo.fabrique.social.gouv.fr/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run tests
        env:
          YARN_IGNORE_NODE: "1"
        run: |
          cd front
          yarn install
          yarn test
