name: Build Android App

on:
  push:
    branches: develop-without-expo


jobs:
  mobile-tests:
    name: Mobile Tests
    runs-on: ubuntu-latest
    env:
      MATOMO_APPLICATION_ID: 46
      MATOMO_ENABLED: false
      MATOMO_URL: https://matomo.fabrique.social.gouv.fr/
    steps:

    - uses: actions/checkout@v2

    # - name: Run mobile tests
    #   run: |
    #       cd front
    #       yarn install
    #       yarn test

    - name: Write key properties
      shell: bash
      run: |
        cd front/android
        echo "$PROD_KEY_PROPERTIES_B64" | base64 --decode > key.properties
      env:
        PROD_KEY_PROPERTIES_B64: ${{ secrets.PROD_KEY_PROPERTIES_B64 }}

    - name: Write key store
      shell: bash
      run: |
        cd front/android
        ls -la
        mkdir keystore
        echo "$PROD_KEYSTORE_B64" | base64 --decode > keystore/millejours.jks
      env:
        PROD_KEYSTORE_B64: ${{ secrets.PROD_KEYSTORE_B64 }}

    - name: Build the App
      run: |
        cd front/android
        ./gradlew build
