name: Mobile Tests

on:
  pull_request:

jobs:
  mobile-tests:
    name: Mobile Tests
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run tests
      run: |
          cd front
          yarn install
          yarn test
