name: 👀 Review
on:
  push:
    branches:
      - "**"
      - "!master"
      - "!main"
      - "!feat/**"
      - "!fix/**"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:

  register:
    name: Build & Register Strapi
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: dev
          dockercontext: ./back/strapi
          imageName: 1000jours/strapi
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./back/strapi/Dockerfile
          
  kontinuous:
    uses: socialgouv/workflows/.github/workflows/use-ks-gh-review.yaml@v1
    secrets: inherit
