name: 👀 Review
on:
  push:
    branches:
      - "**"
      - "!master"
      - "!main"
      - "!feat-**"
      - "!fix-**"
      - "!feat/**"
      - "!fix/**"
      - "!develop"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  build-strapi:
    environment: build-review
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    runs-on: ubuntu-latest
    steps:
      - name: ⏬ Checkout code repository
        uses: actions/checkout@v4

      - name: 📌 Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.REGISTRY_URL }}/${{ vars.PROJECT_NAME }}/${{ github.event.repository.name }}/strapi
          tags: |
            type=sha,prefix=persist-,format=long,enable=${{ 
              github.ref_name == 'dev' || 
              github.ref_name == 'develop' || 
              github.ref_name == 'preprod' || 
              github.ref_name == 'main' || 
              github.ref_name == 'master'
            }},priority=840
            type=sha,prefix=sha-,format=long,priority=890
            type=ref,event=branch,priority=600

      - name: 📦 Build and push Docker image for strapi
        uses: socialgouv/workflows/actions/buildkit@v1
        with:
          context: "./back/strapi"
          dockerfile: "Dockerfile"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          registry: "${{ vars.REGISTRY_URL }}"
          registry-username: "${{ secrets.REGISTRY_USERNAME }}"
          registry-password: "${{ secrets.REGISTRY_PASSWORD }}"
          buildkit-cert-ca: "${{ secrets.BUILDKIT_CERT_CA }}"
          buildkit-cert: "${{ secrets.BUILDKIT_CERT }}"
          buildkit-cert-key: "${{ secrets.BUILDKIT_CERT_KEY }}"
          buildkit-svc-count: ${{ vars.BUILDKIT_SVC_COUNT }}
          buildkit-daemon-address: ${{ vars.BUILDKIT_DAEMON_ADDRESS }}

  kontinuous:
    needs: [build-strapi]
    name: "Deploy on Kubernetes 🐳"
    uses: socialgouv/workflows/.github/workflows/use-ks-gh-review-atlas.yaml@v1
    secrets: inherit
