name: Production

on:
  push:
    tags:
      - v*

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  ##############################################################################
  ## BUILD AND REGISTER APPLICATION IMAGE
  ##############################################################################
  register:
    name: Build & Register application
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: prod
          dockercontext: ./back/strapi
          imageName: 1000jours/strapi
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./back/strapi/Dockerfile

  ##############################################################################
  ## DEPLOY PRODUCTION APPLICATION
  ##############################################################################
  deploy-prod:
    name: Deploy production
    runs-on: ubuntu-latest
    needs: [register]
    environment:
      name: production
      url: https://backoffice-les1000jours.fabrique.social.gouv.fr
    steps:
      - uses: SocialGouv/kontinuous/.github/actions/deploy-via-github@v1
        with:
          environment: prod
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
          ciNamespace: "${{ secrets.RANCHER_PROJECT_NAME }}-ci"
          disableDiff: "true"
