on:
  push:
    branches:
      - master
      - branch-*
  pull_request:
      types: [opened, synchronize, reopened]
name: SonarCloud analysis
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=SocialGouv
          -Dsonar.projectKey=SocialGouv_1000jours
          -Dsonar.exclusions=**/schema.graphql.js
