name: Test
on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Manual workflow"

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.GOOGLE_MAPS_API_KEY }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.GOOGLE_MAPS_API_KEY}} | sed 's/./& /g'
